# Generated by Django 3.2.15 on 2022-09-14 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_mail_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail_template',
            options={'ordering': ['date_added']},
        ),
        migrations.AddField(
            model_name='mail_template',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mail_template',
            name='template',
            field=models.FileField(upload_to='Mailing', validators=[django.core.validators.FileExtensionValidator(['html'])]),
        ),
    ]
