# Generated by Django 3.2.15 on 2022-09-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220914_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mail_template',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('uk', 'Українська'), ('ru', 'Русский')], max_length=10),
        ),
    ]
