version: "3.9"
services:
  web:
    build: ./
    restart: always
#    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py initadmin && python manage.py collectstatic && gunicorn KinoCMS.wsgi:application --bind 0.0.0.0:8000"
    command: python manage.py migrate
#    command: python manage.py collectstatic --no-input
#    command: python manage.py initadmin
#    command: sh -c "python manage.py migrate && python manage.py initadmin && python manage.py collectstatic --no-input && gunicorn KinoCMS.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/kino_cms
      - ./static:/usr/src/kino_cms/static
      - ./media:/usr/src/kino_cms/media
#      - static_volume:/home/vlad/PycharmProjects/KinoCMS/static
#      - media_volume:/home/vlad/PycharmProjects/KinoCMS/media
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./.env
    ports:
      - "5432:5432"


#  nginx:
#    build: ./nginx
#    restart: on-failure
#    volumes:
#      - ./static:/static
#      - ./media:/media
#    ports:
#      - "81:80"
#    depends_on:
#      - web
volumes:
  postgres_data: