version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn KinoCMS.wsgi:application --bind 0.0.0.0:8000
#    command: python manage.py collectstatic --no-input
#    command: bash -c "python manage.py migrate && python manage.py initadmin && gunicorn KinoCMS.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
      - static_files:/app/static
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:14.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}


  nginx:
    build: ./nginx
    restart: always
    volumes:
      - static_files:/app/static
      - media_files:/app/media/
    ports:
      - "8080:80"
    depends_on:
      - web
volumes:
  media_files:
  static_files:
  postgres_data:
