# Generated by Django 4.0.6 on 2022-08-15 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery_seo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('conditions', models.TextField()),
                ('logo', models.ImageField(upload_to='cinema')),
                ('banner_image', models.ImageField(upload_to='cinema')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery_seo.image_gallery')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gallery_seo.seo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(null=True)),
                ('main_image', models.ImageField(upload_to='films')),
                ('trailer_url', models.URLField(blank=True)),
                ('type_2D', models.BooleanField()),
                ('type_3D', models.BooleanField()),
                ('type_IMAX', models.BooleanField()),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery_seo.image_gallery')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gallery_seo.seo')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('scheme', models.ImageField(upload_to='')),
                ('banner_image', models.ImageField(upload_to='')),
                ('cinema', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.cinema')),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gallery_seo.image_gallery')),
                ('seo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gallery_seo.seo')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.SmallIntegerField()),
                ('time', models.TimeField()),
                ('type_3D', models.BooleanField()),
                ('type_DBOX', models.BooleanField()),
                ('type_VIP', models.BooleanField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.film')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
            ],
        ),
    ]
