# Generated by Django 4.0.6 on 2022-08-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='phone',
            field=models.CharField(max_length=19),
        ),
        migrations.AlterField(
            model_name='hall',
            name='banner_image',
            field=models.ImageField(upload_to='halls'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='scheme',
            field=models.ImageField(upload_to='halls'),
        ),
    ]
