# Generated by Django 4.0.6 on 2022-08-31 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='time',
        ),
        migrations.AddField(
            model_name='session',
            name='date_time',
            field=models.DateTimeField(),
            preserve_default=False,
        ),
    ]
