# Generated by Django 4.0.6 on 2022-08-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_alter_cinema_phone_alter_hall_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='cinema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cinema.cinema'),
        ),
    ]
