# Generated by Django 4.0.6 on 2022-08-21 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_alter_hall_cinema'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 21, 12, 51, 58, 15017)),
            preserve_default=False,
        ),
    ]
