# Generated by Django 3.2.15 on 2022-09-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20220918_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='conditions_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cinema',
            name='conditions_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hall',
            name='name_uk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
