# Generated by Django 3.2.15 on 2022-09-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20220918_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='scheme',
            field=models.TextField(),
        ),
    ]
