# Generated by Django 4.0.6 on 2022-08-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news_promo',
            old_name='url',
            new_name='trailer_url',
        ),
    ]
