# Generated by Django 4.0.6 on 2022-09-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_page',
            name='coords',
            field=models.TextField(),
        ),
    ]
