# Generated by Django 4.0.6 on 2022-08-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_url_news_promo_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_promo',
            name='date',
            field=models.DateField(),
        ),
    ]
