# Generated by Django 3.2.15 on 2022-09-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_contact_page_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_page',
            name='address_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact_page',
            name='address_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='contact_page',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contact_page',
            name='name_uk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='main_page',
            name='seo_text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='main_page',
            name='seo_text_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news_promo',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news_promo',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news_promo',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='news_promo',
            name='name_uk',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='other_page',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='other_page',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='other_page',
            name='name_ru',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='other_page',
            name='name_uk',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
