# Generated by Django 3.2.15 on 2022-09-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20220920_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_promo',
            name='type',
            field=models.CharField(choices=[('News', 'news'), ('Promo', 'promo')], max_length=10),
        ),
    ]
