# Generated by Django 3.2.15 on 2022-09-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_news_promo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_promo',
            name='type',
            field=models.CharField(choices=[('news', 'News'), ('promo', 'Promo')], max_length=10),
        ),
    ]
