# Generated by Django 3.2.15 on 2022-10-26 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_news_promo_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='other_page',
            options={'ordering': ['-pk']},
        ),
    ]
