# Generated by Django 3.2.15 on 2022-10-26 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_other_page_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='other_page',
            options={'ordering': ['name']},
        ),
    ]
