# Generated by Django 4.0.6 on 2022-08-17 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner')),
                ('color', models.CharField(max_length=7)),
                ('is_image', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banner_collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation_speed', models.TimeField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Banner_news_collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Banner_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner')),
                ('url', models.URLField()),
                ('banner_news_collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baners.banner_news_collection')),
            ],
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('url', models.URLField()),
                ('text', models.CharField(max_length=100)),
                ('banner_collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='baners.banner_collection')),
            ],
        ),
    ]
