# Generated by Django 4.0.6 on 2022-08-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner_collection',
            name='rotation_speed',
            field=models.CharField(choices=[('5000', '5s'), ('10000', '10s'), ('15000', '15s'), ('20000', '20s'), ('30000', '30s'), ('45000', '45s'), ('60000', '1m'), ('120000', '2m'), ('300000', '5m')], default='5s', max_length=10),
        ),
        migrations.AlterField(
            model_name='banner_news_collection',
            name='rotation_speed',
            field=models.CharField(choices=[('5000', '5s'), ('10000', '10s'), ('15000', '15s'), ('20000', '20s'), ('30000', '30s'), ('45000', '45s'), ('60000', '1m'), ('120000', '2m'), ('300000', '5m')], default='5s', max_length=10),
        ),
    ]
