# Generated by Django 4.0.6 on 2022-08-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner_collection',
            name='rotation_speed',
            field=models.CharField(choices=[('5s', '5s'), ('10s', '10s'), ('15s', '15s')], default='5s', max_length=10),
        ),
        migrations.AlterField(
            model_name='banner_news_collection',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='banner_news_collection',
            name='rotation_speed',
            field=models.CharField(choices=[('5s', '5s'), ('10s', '10s'), ('15s', '15s')], default='5s', max_length=10),
        ),
    ]
